Dockerfile updated to pass all the Red Hat Certification requirements
IBM/template-node-typescript pull request #27
Opened 2021-04-26 05:13 UTC by manojjahgirdar

The Dockerfile now passes the following Tests on Red Hat Certification:
- [x] `is_rhel`
- [x] `has_licenses`
- [x] `rpm_list_successful`
- [x] `not_running_privileged`
- [x] `not_running_as_root`
- [x] `name_label_exists`
- [x] `vendor_label_exists`
- [x] `version_label_exists`
- [x] `release_label_exists`
- [x] `good_tags`
- [x] `good_layer_count`
- [x] `free_of_critical_vulnerabilities`
- [ ] `free_of_important_vulnerabilities`
- [x] `non_inherited_base_label_name`
- [x] `non_inherited_base_label_vendor`
- [x] `non_inherited_base_label_description`
- [x] `non_inherited_base_label_summary`
- [x] `has_base_rh_image`
- [x] `ubi_content_ok`
- [x] `has_under_40_layers`

The test `free_of_critical_vulnerabilities` is failing because there is a [known issue](https://github.ibm.com/operator-guild/docs/issues/23).

2021-04-28 15:43 UTC, bwoolf1 commented
Manoj: Looking at https://github.com/IBM/template-node-typescript/pull/27/commits/d4a9813e1ec9cf24ac4967255603d812826831ce, lots of good stuff here. There's a couple of things I'm confused about though.

The Dockerfile is adding security updates and license files to the builder image. Shouldn't those go in the second image, the one that will be deployed? Also, it probably doesn't need to be root to run `WORKDIR /opt/app-root/src`, I would think default could do that.

Also, your file set currently includes `.DS_Store`. If that's not needed, let's take it out. Maybe add it to .gitignore to prevent this in the future.

Nice progress. Thanks!

2021-04-28 17:06 UTC, manojjahgirdar commented
> Manoj: Looking at [d4a9813](https://github.com/IBM/template-node-typescript/commit/d4a9813e1ec9cf24ac4967255603d812826831ce), lots of good stuff here. There's a couple of things I'm confused about though.
> 
> The Dockerfile is adding security updates and license files to the builder image. Shouldn't those go in the second image, the one that will be deployed? Also, it probably doesn't need to be root to run `WORKDIR /opt/app-root/src`, I would think default could do that.
> 
> Also, your file set currently includes `.DS_Store`. If that's not needed, let's take it out. Maybe add it to .gitignore to prevent this in the future.
> 
> Nice progress. Thanks!

Fixed these issues. Thanks

2021-04-28 17:19 UTC, bwoolf1 commented
> Fixed these issues. Thanks

Manoj: I see where you deleted `.DS_Store` and moved the WORKDIR command so that it's run by the `default` user. Good, thanks.

I'm still confused about where the security update and license stuff is being done. It looks like the code is doing the right stuff but to the wrong image. It's updating the builder image. Seems to me it should be updating the second image, the one with the labels and exposed port, etc.

To make sure I'm explaining what I mean: This code is between the two FROM statements:
```
FROM ...
USER root
## comment the below line if there are no sec severities
RUN dnf -y update-minimal --security --sec-severity=Important --sec-severity=Critical && dnf clean all
COPY ./licenses /licenses
USER default
...
FROM ...
...
```


Shouldn't it be after the second from statement? Or if it's in the right place, please explain.

2021-04-28 19:35 UTC, bwoolf1 commented
Minoj: The value for the `name` label should be of the form `<namespace>/<image-name>`. For example, it's `ubi8/openjdk-11` in the Java UBI. So "Typescript Microservice" (in https://github.com/IBM/template-node-typescript/pull/27/commits/25de4945a52c9b4a94027ea152ef9077ba284d57) is an OK example but could be better.

For this image, it's not a base image stored in a registry anywhere, so the image namespace and name are not yet determined. So for this example, the name of the GitHub org and repo is probably as good a default as any: `ibm/template-node-typescript`. If the image (with no application) were stored in a registry, that's probably what we would name it.

So let's change:
```
LABEL name="Typescript Microservice"
```
to:
```
LABEL name="ibm/template-node-typescript"
```

2021-04-28 19:41 UTC, bwoolf1 commented
Manoj: Likewise, Red Hat doesn't put the letter "v" in their version name, so let's not show that in our example. For example, `ubi8/openjdk-11:1.3-15` sets version="1.3" and release="15".

So let's change:
```
      version="v1.0.0" \
```
to:
```
      version="1.0.0" \
```

2021-04-29 14:16 UTC, manojjahgirdar commented
Bobby: Answering your questions: 
> I'm still confused about where the security update and license stuff is being done.

I believe as the base image is the same in both the `FROM` commands, updating of image security contents, copying the license can be done anywhere. However keeping it consistent across all the starter kit templates, I'll move it after the 2nd `FROM` statement.

> The value for the name label should be of the form <namespace>/<image-name>. For example, it's ubi8/openjdk-11 in the Java UBI. So "Typescript Microservice" (in 25de494) is an OK example but could be better.

Ok noted, I'll change the name label.

> Likewise, Red Hat doesn't put the letter "v" in their version name, so let's not show that in our example. For example, ubi8/openjdk-11:1.3-15 sets version="1.3" and release="15".

Ok makes sense, I'll change the version and release tags accordingly.

Thanks for the Feedback.

2021-04-29 18:37 UTC, bwoolf1 commented
LGTM. Nice job.

Catalyst team, what do you think of the default values for version and release being the same as those for the UBI the image is built from?

2021-05-04 15:24 UTC, bwoolf1 commented
@csantanapr: What updates do you want to this PR to approve it? Please document these requests for @manojjahgirdar. Thanks.

2021-05-05 07:53 UTC, manojjahgirdar commented
- I have commented the updating image security content command.
- Here is a confirmation that the Dockerfile builds successfully: 
![Screenshot 2021-05-05 at 12 39 21 PM](https://user-images.githubusercontent.com/52746337/117111248-eef1d500-ada4-11eb-8a59-551182e49815.png)

2021-05-05 11:59 UTC, csantanapr commented
Please verify app still works on OpenShift, build and deploy with Toolkit

2021-05-05 15:14 UTC, manojjahgirdar commented
> Please verify app still works on OpenShift, build and deploy with Toolkit

@csantanapr,

I tried it, and it fails on `tag-release`, it says: 
```
ERROR fatal: tag 'v1.0.4' already exists
```
![Screenshot 2021-05-05 at 8 29 32 PM](https://user-images.githubusercontent.com/52746337/117164869-a3f6b280-ade2-11eb-8720-b9b362c431e8.png)

What does this mean?

2021-05-06 21:06 UTC, bwoolf1 commented
@manojjahgirdar: Now that your pipelines are able to log into Artifactory, is this pipeline able to run successfully? If so, please post a screenshot.

`ERROR fatal: tag 'v1.0.4' already exists` means that the pipeline tried to use a tag that it has already used. This might happen if you reran the same pipeline run (I'm not sure). Try making a change to your code and merging that to your branch, which will trigger the pipeline to start a new run.

2021-05-07 05:43 UTC, manojjahgirdar commented
> @manojjahgirdar: Now that your pipelines are able to log into Artifactory, is this pipeline able to run successfully? If so, please post a screenshot.
> 
> `ERROR fatal: tag 'v1.0.4' already exists` means that the pipeline tried to use a tag that it has already used. This might happen if you reran the same pipeline run (I'm not sure). Try making a change to your code and merging that to your branch, which will trigger the pipeline to start a new run.

@bwoolf1, this still fails with the same error.

2021-05-07 17:13 UTC, manojjahgirdar commented
@csantanapr Vulnerability Advisor now finds no issues, here is proof.
![Screenshot 2021-05-07 at 10 41 01 PM](https://user-images.githubusercontent.com/52746337/117485127-a3e2e800-af85-11eb-994a-7b74977ee1ab.png)

2021-05-07 17:16 UTC, manojjahgirdar commented
@csantanapr Vulnerability Advisor now finds no issues, here is proof.
![Screenshot 2021-05-07 at 10 45 12 PM](https://user-images.githubusercontent.com/52746337/117485548-194eb880-af86-11eb-8cfa-e30cac6ed4e6.png)

2021-05-10 15:46 UTC, csantanapr requested changes
extra change in package.json

2021-05-10 15:46 UTC, csantanapr commented on package.json
> +  "name": "template-node-typescript-mj",
```suggestion
  "name": "template-node-typescript",
```

remove `mj`

2021-05-12 12:55 UTC, csantanapr approved these changes

2021-05-13 03:34 UTC, csantanapr approved these changes
LGTM

2021-05-13 03:34 UTC, merged